cam_model: Pinhole                       # 相机模型类型 (针孔相机)
cam_width: 1280                          # 相机图像宽度 (像素)
cam_height: 1024                         # 相机图像高度 (像素)
scale: 0.5                               # 图像缩放比例
cam_fx: 1293.56944                       # 相机焦距在x轴上的像素值
cam_fy: 1293.3155                        # 相机焦距在y轴上的像素值
cam_cx: 626.91359                        # 相机主点在x轴上的坐标
cam_cy: 522.799224                       # 相机主点在y轴上的坐标
cam_d0: -0.076160                        # 径向畸变系数 d0
cam_d1: 0.123001                         # 径向畸变系数 d1
cam_d2: -0.00113                         # 径向畸变系数 d2
cam_d3: 0.000251                         # 切向畸变系数 d3